name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Restore dependencies
        run: npm ci
        
      - name: Build
        id: build
        run: node ./build.js

      - name: Create Release
        uses: softprops/action-gh-release@v2
        id: create_release
        with:
          body: |
            **Note:** This release is not signed and will not be loaded by the browser directly.
            The extension is currently available through the Firefox Add-ons gallery:
            - [Firefox addons](https://addons.mozilla.org/en-GB/firefox/search/?q=Azure%20DevOps%20icon&type=extension)

            The Chrome/Edge extension was removed from the Chrome Web Store because of a claim by Microsoft and thus has to be installed manually.
          name: ${{ steps.build.outputs.PKG_VERSION }}
          tag_name: ${{ steps.build.outputs.PKG_VERSION }}
          files: |
              dist/firefox/firefox_azure_devops_icons-${{ steps.build.outputs.PKG_VERSION }}.zip
              dist/chrome/chrome_azure_devops_icons-${{ steps.build.outputs.PKG_VERSION }}.zip
          generate_release_notes: true
          make_latest: true